galaxy_info:
  author: Dusan Matejka
  description: role to install and configure rsyslog on the managed host
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic

  galaxy_tags:
    - rsyslog

dependencies: []
