galaxy_info:
  author: Dusan Matejka
  description: Simple docker installer with syslog logging setup
  issue_tracker_url: https://github.com/D3DeFi/playground.git
  license: MIT
  min_ansible_version: 2.1
  platforms:
  - name: Ubuntu
    versions:
    - xenial
    - bionic
  galaxy_tags:
    - docker
    - docker-syslog

dependencies: []
