---
# tasks file for rsyslog
- name: Ensure rsyslog package is installed
  apt:
    name: '{{ rsyslog_package }}'
    state: present

- name: Ensure rsyslog.d subdirectory exists
  file:
    path: /etc/rsyslog.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Ensure rsyslog spool directory exists
  file:
    path: '{{ rsyslog_work_dir }}'
    state: directory
    owner: syslog
    group: adm
    mode: 0700

- name: Upload rsyslog configuration
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: 0644
    validate: '/usr/sbin/rsyslogd -N1 -f %s'
  notify: Restart rsyslog

- name: Upload standard system log configuration
  template:
    src: 50-default.conf.j2
    dest: /etc/rsyslog.d/50-default.conf
    owner: root
    group: root
    mode: 0644
    validate: '/usr/sbin/rsyslogd -N1 -f %s'
  notify: Restart rsyslog

- name: Enable remote logging
  template:
    src: 60-remote-log.conf.j2
    dest: /etc/rsyslog.d/60-remote-log.conf
    owner: root
    group: root
    mode: 0644
    validate: '/usr/sbin/rsyslogd -N1 -f %s'
  notify: Restart rsyslog
  when:
    - rsyslog_remote_server is defined
    - rsyslog_remote_server != ""

- name: Configure custom logging
  template:
    src: custom-log.conf.j2
    dest: /etc/rsyslog.d/{{ _rsys_prog_name }}.conf
    owner: root
    group: root
    mode: 0644
    validate: '/usr/sbin/rsyslogd -N1 -f %s'
  loop: '{{ rsyslog_custom_logs }}'
  vars:
    _rsys_prog_name: '{{ item["progname"] }}'
    _rsys_log_dest: '{{ item["dest"] }}'
  notify: Restart rsyslog
  when:
    - rsyslog_custom_logs|length > 0

- name: Setup rsyslog logrotate
  include_tasks: logrotate.yml
